### ISSUE TITLE
Partition and Row Key's from the base class retrieved as Nulls

### ISSUE THREAD

**Issue by ajoylabroo** [s-innovations/azure-table-storage-repository-pattern#3]
Accessing Partition and Row Key properties of the base class always returns null. Look at the below sample:

Here is the `Product` class:

``` csharp
public class Product : TableEntity
{
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        public string Store { get; set; }
        public string Category { get; set; }
}
```

Here is the `ProductContext` class:

``` csharp
public class ProductContext : TableStorageContext
{
        private static IConfiguration _config;

        public ProductContext(IConfiguration config) : base(CloudStorageAccount.Parse(config["Data:DefaultConnection:StorageConnectionString"]))
        {
            _config = config;
            this.InsertionMode = InsertionMode.AddOrMerge;
            Table.SetInitializer(new CreateTablesIfNotExists<ProductContext>());
        }
        protected override void OnModelCreating(TableStorageModelBuilder modelbuilder)
        {
            modelbuilder.Entity<Product>()
                .HasKeys(pk => pk.Category, rk => string.Format("{0}_{1}", rk.Store.ToLower(), rk.ProductId))
                .ToTable(_config["Data:CloudTables:Product"]);

            base.OnModelCreating(modelbuilder);
        }
        public ITableRepository<Product> Products { get; set; }
}
```

Now, if you have a function like below:

``` csharp
public IEnumerable<Product> GetProducts(string category, int pageSize, int pageNumber, string orderBy)
{
         var context = new ProductContext(_config);
         var products = (from f in context.Products
                            where f.PartitionKey == category
                            select f).ToArray();
         return products;
}
```

In the above function, every single element within `products` has a `NULL` value in the following base class properties:

```
products[0].PartitionKey -> NULL
products[0].RowKey -> NULL
products[0].Timestamp -> NULL
```

Any ideas?

**Comment by pksorensen** [comment]
Take a look at this example:

https://github.com/s-innovations/azure-table-storage-repository-pattern/blob/master/S-Innovations.Azure.TableStorageRepository.Test/UnitTest5.cs#L37

The idea behind hte lib was to seperate out the context of row/part keys from developers who are not configuring the model.

Meaning if you skip the inheritance of TableEntity, then the lib will automatically map row/part keys to its properties.

For this to work properly, you have to specify the haskeys like this:
`.HasKeys(pk => pk.Category, rk =>new {  rk.Store, rk.ProductId})`
which will then put store and productId into the row column of table storage.

But I dont have a way to include the ToLower() in your example. If its needed, i would do it in the application code or in get/setter of the model.

**Comment by ajoylabroo** [comment]
Thanks.
